title: frantic.im
author: Alex Kotliarskyi
author_tagline: software engineer at Facebook (React&nbsp;Native, Oculus) with interest in development experience
permalink: :title
email: contact@frantic.im
twitter: https://twitter.com/alex_frantic
description: Occasional posts on technology and stuff
baseurl: ""
url: "http://frantic.im"
markdown: kramdown
highlighter: rouge
exclude:
  - "*.sketch"
  - "vendor"
